### ISSUE TITLE
Cannot convert undefined or null to object at Function.keys at Transport.queryParser

### ISSUE THREAD

**Issue by ddbhagat** [newrelic/serverless-newrelic-lambda-layers#385] opened 2023-10-17 12:56 UTC
Getting below error out of sudden without any code changes on AWS Lambda.

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Transport.queryParser (/opt/nodejs/node_modules/newrelic/lib/instrumentation/@elastic/elasticsearch.js:58:49)
    at DatastoreShim.parseQuery (/opt/nodejs/node_modules/newrelic/lib/shim/datastore-shim.js:456:35)
    at Transport.queryRecord (/opt/nodejs/node_modules/newrelic/lib/shim/datastore-shim.js:670:25)
    at Transport.wrapper (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:850:33)
    at Client.getApi [as get] (/var/task/node_modules/@elastic/elasticsearch/api/api/get.js:62:25)
    at e.exports.get (/var/task/functions/graphql.js:1:95039)
    at e.exports.get (/var/task/functions/graphql.js:1:120393)
    at Object.part (/var/task/functions/graphql.js:1:39923)
    at field.resolve (/var/task/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:56:26)

**Comment by bizob2828** [comment] 2023-10-17 13:23
Hi @ddbhagat sorry for your troubles. This is a duplicate of https://github.com/newrelic/node-newrelic/issues/1809. We hope to have a fix released this week. I'm going to close this one and I'll let you know when we have released the fix.

**Closed** 2023-10-17 13:23 UTC

**Comment by villelahdenvuo** [comment] 2023-10-18 14:36
@ddbhagat It is a bug in the new elasticsearch instrumentation, perhaps you upgraded but didn't hit this codepath before? We got lucky because it got detected in E2E our tests.
